export type ModelCapability = 'text-to-image' | 'image-to-image' | 'text-to-video' | 'image-to-video'
export type ModelCategory = 'google' | 'flux' | 'bytedance' | 'qwen' | 'wan' | 'ideogram' | 'hidream' | 'rundiffusion' | 'stability' | 'lykon' | 'openai' | 'minimax' | 'kling' | 'pixverse' | 'vidu'

export interface AIModel {
  id: string
  displayName: string
  category: ModelCategory
  categoryLabel: string
  type: 'image' | 'video'
  capabilities: ModelCapability[]
  credits: number
  togetherPrice: string
  resolution?: string
  duration?: string
  hasAudio?: boolean
  defaultSteps?: number
  supportsImageUrl?: boolean
  supportsFrameImages?: boolean
  description: string
  badge?: string
  enabled: boolean
  aspectRatios: string[]
  maxWidth?: number
  maxHeight?: number
}

const CATEGORY_LABELS: Record<ModelCategory, string> = {
  google: 'Google',
  flux: 'Black Forest Labs',
  bytedance: 'ByteDance',
  qwen: 'Qwen / Alibaba',
  wan: 'Wan-AI',
  ideogram: 'Ideogram',
  hidream: 'HiDream',
  rundiffusion: 'RunDiffusion',
  stability: 'Stability AI',
  lykon: 'Lykon',
  openai: 'OpenAI',
  minimax: 'MiniMax',
  kling: 'Kuaishou / Kling',
  pixverse: 'PixVerse',
  vidu: 'Vidu',
}

const DEFAULT_IMAGE_ASPECT_RATIOS = ['1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '4:5', '5:4', '21:9']
const DEFAULT_VIDEO_ASPECT_RATIOS = ['16:9', '9:16', '1:1']

// ---------------------------------------------------------------------------
// Image Models (32 total)
// ---------------------------------------------------------------------------

const IMAGE_MODELS: AIModel[] = [
  // ---- Google ----
  {
    id: 'google/imagen-4.0-ultra',
    displayName: 'Imagen 4.0 Ultra',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 25,
    togetherPrice: '$0.06/MP',
    supportsImageUrl: false,
    description: 'Google Imagen 4.0 Ultra — highest quality Google image model with exceptional detail and prompt adherence.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'google/imagen-4.0-preview',
    displayName: 'Imagen 4.0 Preview',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 15,
    togetherPrice: '$0.04/MP',
    supportsImageUrl: false,
    description: 'Google Imagen 4.0 Preview — high quality Google image generation at a balanced cost.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'google/imagen-4.0-fast',
    displayName: 'Imagen 4.0 Fast',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 8,
    togetherPrice: '$0.02/MP',
    supportsImageUrl: false,
    description: 'Google Imagen 4.0 Fast — speed-optimized Google image generation for rapid iteration.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'google/flash-image-2.5',
    displayName: 'Flash Image 2.5',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 15,
    togetherPrice: '$0.039/MP',
    supportsImageUrl: true,
    description: 'Google Flash Image 2.5 — fast image generation and editing with image-to-image support.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'google/gemini-3-pro-image',
    displayName: 'Gemini 3 Pro Image',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 20,
    togetherPrice: '$0.134/image',
    supportsImageUrl: true,
    description: 'Google Gemini 3 Pro Image — multimodal image generation powered by the Gemini 3 Pro model.',
    badge: 'NEW',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- Black Forest Labs / FLUX ----
  {
    id: 'black-forest-labs/FLUX.2-pro',
    displayName: 'FLUX.2 Pro',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 20,
    togetherPrice: '$0.05/MP',
    supportsImageUrl: false,
    description: 'FLUX.2 Pro — professional-grade image generation with excellent prompt following and image-to-image.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.2-dev',
    displayName: 'FLUX.2 Dev',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 10,
    togetherPrice: '$0.025/MP',
    supportsImageUrl: false,
    description: 'FLUX.2 Dev — development version of FLUX.2 with strong quality at a lower price point.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.2-flex',
    displayName: 'FLUX.2 Flex',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 10,
    togetherPrice: '$0.025/MP',
    supportsImageUrl: false,
    description: 'FLUX.2 Flex — flexible FLUX.2 variant optimized for varied aspect ratios and image-to-image.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.2-max',
    displayName: 'FLUX.2 Max',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 25,
    togetherPrice: '$0.07/MP',
    supportsImageUrl: false,
    defaultSteps: 50,
    description: 'FLUX.2 Max — highest quality FLUX.2 model with 50-step default for maximum detail.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1.1-pro',
    displayName: 'FLUX 1.1 Pro',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 15,
    togetherPrice: '$0.04/MP',
    supportsImageUrl: false,
    description: 'FLUX 1.1 Pro — proven professional FLUX model with reliable quality and image-to-image support.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-schnell',
    displayName: 'FLUX.1 Schnell',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 3,
    togetherPrice: '$0.0027/MP',
    supportsImageUrl: false,
    defaultSteps: 4,
    description: 'FLUX.1 Schnell — ultra-fast 4-step generation for rapid prototyping at minimal cost.',
    badge: 'FAST',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-dev',
    displayName: 'FLUX.1 Dev',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 8,
    togetherPrice: '$0.025/MP',
    supportsImageUrl: false,
    defaultSteps: 28,
    description: 'FLUX.1 Dev — open-weight FLUX model with 28-step default for quality text-to-image generation.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-kontext-pro',
    displayName: 'FLUX Kontext Pro',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 15,
    togetherPrice: '$0.04/MP',
    supportsImageUrl: true,
    defaultSteps: 28,
    description: 'FLUX Kontext Pro — context-aware image editing and generation, optimized for image-to-image workflows.',
    badge: 'POPULAR',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-kontext-max',
    displayName: 'FLUX Kontext Max',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 25,
    togetherPrice: '$0.08/MP',
    supportsImageUrl: true,
    defaultSteps: 28,
    description: 'FLUX Kontext Max — highest quality context-aware editing with maximum detail for image-to-image.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-kontext-dev',
    displayName: 'FLUX Kontext Dev',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 10,
    togetherPrice: '$0.025/MP',
    supportsImageUrl: true,
    defaultSteps: 28,
    description: 'FLUX Kontext Dev — development context-aware model for affordable image-to-image editing.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-krea-dev',
    displayName: 'FLUX.1 Krea Dev',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 10,
    togetherPrice: '$0.025/MP',
    supportsImageUrl: false,
    defaultSteps: 30,
    description: 'FLUX.1 Krea Dev — Krea-tuned FLUX variant with 30-step default and image-to-image support.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'black-forest-labs/FLUX.1-canny-pro',
    displayName: 'FLUX.1 Canny Pro',
    category: 'flux',
    categoryLabel: CATEGORY_LABELS.flux,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 18,
    togetherPrice: '$0.05/MP',
    supportsImageUrl: false,
    description: 'FLUX.1 Canny Pro — edge-guided image generation using canny edge detection for structural control.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- ByteDance ----
  {
    id: 'ByteDance-Seed/Seedream-4.0',
    displayName: 'Seedream 4.0',
    category: 'bytedance',
    categoryLabel: CATEGORY_LABELS.bytedance,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 12,
    togetherPrice: '$0.03/MP',
    supportsImageUrl: false,
    description: 'ByteDance Seedream 4.0 — latest generation image model with strong text rendering and image-to-image.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'ByteDance-Seed/Seedream-3.0',
    displayName: 'Seedream 3.0',
    category: 'bytedance',
    categoryLabel: CATEGORY_LABELS.bytedance,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 8,
    togetherPrice: '$0.018/MP',
    supportsImageUrl: false,
    description: 'ByteDance Seedream 3.0 — reliable image generation with image-to-image at a great price.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'ByteDance/SeedEdit',
    displayName: 'SeedEdit',
    category: 'bytedance',
    categoryLabel: CATEGORY_LABELS.bytedance,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 12,
    togetherPrice: '$0.03/MP',
    supportsImageUrl: true,
    description: 'ByteDance SeedEdit — specialized image editing model for precise modifications to existing images.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- Qwen / Alibaba ----
  {
    id: 'Qwen/Qwen-Image',
    displayName: 'Qwen Image',
    category: 'qwen',
    categoryLabel: CATEGORY_LABELS.qwen,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 5,
    togetherPrice: '$0.0058/MP',
    supportsImageUrl: false,
    description: 'Qwen Image — affordable text-to-image generation from Alibaba Qwen team.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'Qwen/Qwen-Image-Edit',
    displayName: 'Qwen Image Edit',
    category: 'qwen',
    categoryLabel: CATEGORY_LABELS.qwen,
    type: 'image',
    capabilities: ['text-to-image', 'image-to-image'],
    credits: 3,
    togetherPrice: '$0.0032/MP',
    supportsImageUrl: true,
    description: 'Qwen Image Edit — ultra-affordable image editing with image-to-image support.',
    badge: 'CHEAPEST',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- Wan-AI ----
  {
    id: 'Wan-AI/Wan-2.6-Image',
    displayName: 'Wan 2.6 Image',
    category: 'wan',
    categoryLabel: CATEGORY_LABELS.wan,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 12,
    togetherPrice: '$0.03/MP',
    supportsImageUrl: false,
    description: 'Wan 2.6 Image — Wan-AI image generation with image-to-image support.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- Ideogram ----
  {
    id: 'ideogram/ideogram-3.0',
    displayName: 'Ideogram 3.0',
    category: 'ideogram',
    categoryLabel: CATEGORY_LABELS.ideogram,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 22,
    togetherPrice: '$0.06/MP',
    supportsImageUrl: false,
    description: 'Ideogram 3.0 — excellent text rendering and typography in generated images.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- HiDream ----
  {
    id: 'HiDream-ai/HiDream-I1-Full',
    displayName: 'HiDream I1 Full',
    category: 'hidream',
    categoryLabel: CATEGORY_LABELS.hidream,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 5,
    togetherPrice: '$0.009/MP',
    supportsImageUrl: false,
    description: 'HiDream I1 Full — full-quality HiDream image generation at an affordable price.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'HiDream-ai/HiDream-I1-Dev',
    displayName: 'HiDream I1 Dev',
    category: 'hidream',
    categoryLabel: CATEGORY_LABELS.hidream,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 3,
    togetherPrice: '$0.0045/MP',
    supportsImageUrl: false,
    description: 'HiDream I1 Dev — development HiDream model balancing quality and speed.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'HiDream-ai/HiDream-I1-Fast',
    displayName: 'HiDream I1 Fast',
    category: 'hidream',
    categoryLabel: CATEGORY_LABELS.hidream,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 2,
    togetherPrice: '$0.0032/MP',
    supportsImageUrl: false,
    description: 'HiDream I1 Fast — speed-optimized HiDream model for rapid generation.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- RunDiffusion ----
  {
    id: 'RunDiffusion/Juggernaut-pro-flux',
    displayName: 'Juggernaut Pro',
    category: 'rundiffusion',
    categoryLabel: CATEGORY_LABELS.rundiffusion,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 3,
    togetherPrice: '$0.0049/MP',
    supportsImageUrl: false,
    description: 'Juggernaut Pro — community-favorite FLUX fine-tune with photorealistic output.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'Rundiffusion/Juggernaut-Lightning-Flux',
    displayName: 'Juggernaut Lightning',
    category: 'rundiffusion',
    categoryLabel: CATEGORY_LABELS.rundiffusion,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 2,
    togetherPrice: '$0.0017/MP',
    supportsImageUrl: false,
    description: 'Juggernaut Lightning — ultra-fast Juggernaut variant for rapid photorealistic generation.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- Stability AI ----
  {
    id: 'stabilityai/stable-diffusion-3-medium',
    displayName: 'Stable Diffusion 3',
    category: 'stability',
    categoryLabel: CATEGORY_LABELS.stability,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 2,
    togetherPrice: '$0.0019/MP',
    supportsImageUrl: false,
    description: 'Stable Diffusion 3 Medium — Stability AI next-gen architecture with improved text and composition.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
  {
    id: 'stabilityai/stable-diffusion-xl-base-1.0',
    displayName: 'SDXL Base 1.0',
    category: 'stability',
    categoryLabel: CATEGORY_LABELS.stability,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 2,
    togetherPrice: '$0.0019/MP',
    supportsImageUrl: false,
    description: 'SDXL Base 1.0 — widely-used Stable Diffusion XL base model for general image generation.',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },

  // ---- Lykon ----
  {
    id: 'Lykon/DreamShaper',
    displayName: 'DreamShaper',
    category: 'lykon',
    categoryLabel: CATEGORY_LABELS.lykon,
    type: 'image',
    capabilities: ['text-to-image'],
    credits: 1,
    togetherPrice: '$0.0006/MP',
    supportsImageUrl: false,
    description: 'DreamShaper — the most affordable image model, great for stylized and artistic generation.',
    badge: 'CHEAPEST',
    enabled: true,
    aspectRatios: DEFAULT_IMAGE_ASPECT_RATIOS,
  },
]

// ---------------------------------------------------------------------------
// Video Models (22 total)
// ---------------------------------------------------------------------------

const VIDEO_MODELS: AIModel[] = [
  // ---- Google ----
  {
    id: 'google/veo-3.0',
    displayName: 'Google Veo 3.0',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 50,
    togetherPrice: '$1.60/video',
    resolution: '720p',
    duration: '8s',
    supportsFrameImages: true,
    description: 'Google Veo 3.0 — high quality video generation with text-to-video and image-to-video.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'google/veo-3.0-audio',
    displayName: 'Veo 3.0 + Audio',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 90,
    togetherPrice: '$3.20/video',
    resolution: '720p',
    duration: '8s',
    hasAudio: true,
    supportsFrameImages: true,
    description: 'Veo 3.0 with synchronized audio generation — produces video with matching sound effects and music.',
    badge: 'NEW',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'google/veo-3.0-fast',
    displayName: 'Veo 3.0 Fast',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 30,
    togetherPrice: '$0.80/video',
    resolution: '1080p',
    duration: '8s',
    supportsFrameImages: true,
    description: 'Veo 3.0 Fast — speed-optimized 1080p video generation for rapid iteration.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'google/veo-3.0-fast-audio',
    displayName: 'Veo 3.0 Fast + Audio',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 40,
    togetherPrice: '$1.20/video',
    resolution: '1080p',
    duration: '8s',
    hasAudio: true,
    supportsFrameImages: true,
    description: 'Veo 3.0 Fast with audio — rapid 1080p video generation with synchronized sound.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'google/veo-2.0',
    displayName: 'Google Veo 2.0',
    category: 'google',
    categoryLabel: CATEGORY_LABELS.google,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 70,
    togetherPrice: '$2.50/video',
    resolution: '720p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Google Veo 2.0 — premium video generation with cinematic quality.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- OpenAI ----
  {
    id: 'openai/sora-2',
    displayName: 'Sora 2',
    category: 'openai',
    categoryLabel: CATEGORY_LABELS.openai,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 30,
    togetherPrice: '$0.80/video',
    resolution: '720p',
    duration: '8s',
    supportsFrameImages: true,
    description: 'OpenAI Sora 2 — text-to-video and image-to-video with strong prompt understanding.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'openai/sora-2-pro',
    displayName: 'Sora 2 Pro',
    category: 'openai',
    categoryLabel: CATEGORY_LABELS.openai,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 75,
    togetherPrice: '$2.40/video',
    resolution: '1080p',
    duration: '8s',
    supportsFrameImages: true,
    description: 'Sora 2 Pro — premium 1080p video generation from OpenAI with enhanced detail.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- MiniMax ----
  {
    id: 'minimax/video-01-director',
    displayName: 'MiniMax Director',
    category: 'minimax',
    categoryLabel: CATEGORY_LABELS.minimax,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 12,
    togetherPrice: '$0.28/video',
    resolution: '720p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'MiniMax Director — affordable video generation with camera control capabilities.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'minimax/hailuo-02',
    displayName: 'Hailuo 02',
    category: 'minimax',
    categoryLabel: CATEGORY_LABELS.minimax,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 18,
    togetherPrice: '$0.49/video',
    resolution: '768p',
    duration: '10s',
    supportsFrameImages: true,
    description: 'Hailuo 02 — MiniMax video model producing longer 10-second clips at 768p.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- ByteDance ----
  {
    id: 'ByteDance/Seedance-1.0-pro',
    displayName: 'Seedance 1.0 Pro',
    category: 'bytedance',
    categoryLabel: CATEGORY_LABELS.bytedance,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 20,
    togetherPrice: '$0.57/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'ByteDance Seedance 1.0 Pro — 1080p video generation with strong motion quality.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'ByteDance/Seedance-1.0-lite',
    displayName: 'Seedance 1.0 Lite',
    category: 'bytedance',
    categoryLabel: CATEGORY_LABELS.bytedance,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 6,
    togetherPrice: '$0.14/video',
    resolution: '720p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'ByteDance Seedance 1.0 Lite — affordable 720p video generation for quick iterations.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- Kuaishou / Kling ----
  {
    id: 'kwaivgI/kling-2.1-master',
    displayName: 'Kling 2.1 Master',
    category: 'kling',
    categoryLabel: CATEGORY_LABELS.kling,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 30,
    togetherPrice: '$0.92/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Kling 2.1 Master — highest quality Kling model with cinematic 1080p output.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'kwaivgI/kling-2.1-pro',
    displayName: 'Kling 2.1 Pro',
    category: 'kling',
    categoryLabel: CATEGORY_LABELS.kling,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 12,
    togetherPrice: '$0.32/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Kling 2.1 Pro — professional 1080p video generation at a balanced price.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'kwaivgI/kling-2.1-standard',
    displayName: 'Kling 2.1 Standard',
    category: 'kling',
    categoryLabel: CATEGORY_LABELS.kling,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 8,
    togetherPrice: '$0.18/video',
    resolution: '720p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Kling 2.1 Standard — affordable 720p video generation for everyday use.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'kwaivgI/kling-2.0-master',
    displayName: 'Kling 2.0 Master',
    category: 'kling',
    categoryLabel: CATEGORY_LABELS.kling,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 30,
    togetherPrice: '$0.92/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Kling 2.0 Master — proven master-tier video generation with reliable 1080p output.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'kwaivgI/kling-1.6-pro',
    displayName: 'Kling 1.6 Pro',
    category: 'kling',
    categoryLabel: CATEGORY_LABELS.kling,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 12,
    togetherPrice: '$0.32/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Kling 1.6 Pro — stable professional video generation at 1080p resolution.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'kwaivgI/kling-1.6-standard',
    displayName: 'Kling 1.6 Standard',
    category: 'kling',
    categoryLabel: CATEGORY_LABELS.kling,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 8,
    togetherPrice: '$0.19/video',
    resolution: '720p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Kling 1.6 Standard — budget-friendly 720p video generation.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- PixVerse ----
  {
    id: 'pixverse/pixverse-v5',
    displayName: 'PixVerse V5',
    category: 'pixverse',
    categoryLabel: CATEGORY_LABELS.pixverse,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 12,
    togetherPrice: '$0.30/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'PixVerse V5 — 1080p video generation with strong visual quality and motion.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- Wan-AI ----
  {
    id: 'Wan-AI/Wan2.2-T2V-A14B',
    displayName: 'Wan 2.2 Text-to-Video',
    category: 'wan',
    categoryLabel: CATEGORY_LABELS.wan,
    type: 'video',
    capabilities: ['text-to-video'],
    credits: 22,
    togetherPrice: '$0.66/video',
    supportsFrameImages: false,
    description: 'Wan 2.2 Text-to-Video — text-to-video only model from Wan-AI with 14B parameters.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'Wan-AI/Wan2.2-I2V-A14B',
    displayName: 'Wan 2.2 Image-to-Video',
    category: 'wan',
    categoryLabel: CATEGORY_LABELS.wan,
    type: 'video',
    capabilities: ['image-to-video'],
    credits: 12,
    togetherPrice: '$0.31/video',
    supportsFrameImages: true,
    description: 'Wan 2.2 Image-to-Video — image-to-video only model from Wan-AI with 14B parameters.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },

  // ---- Vidu ----
  {
    id: 'vidu/vidu-2.0',
    displayName: 'Vidu 2.0',
    category: 'vidu',
    categoryLabel: CATEGORY_LABELS.vidu,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 12,
    togetherPrice: '$0.28/video',
    resolution: '720p',
    duration: '8s',
    supportsFrameImages: true,
    description: 'Vidu 2.0 — affordable 720p video generation with 8-second duration.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
  {
    id: 'vidu/vidu-q1',
    displayName: 'Vidu Q1',
    category: 'vidu',
    categoryLabel: CATEGORY_LABELS.vidu,
    type: 'video',
    capabilities: ['text-to-video', 'image-to-video'],
    credits: 10,
    togetherPrice: '$0.22/video',
    resolution: '1080p',
    duration: '5s',
    supportsFrameImages: true,
    description: 'Vidu Q1 — quality-focused 1080p video generation at a competitive price.',
    enabled: true,
    aspectRatios: DEFAULT_VIDEO_ASPECT_RATIOS,
  },
]

// ---------------------------------------------------------------------------
// Combined registry
// ---------------------------------------------------------------------------

export const ALL_MODELS: AIModel[] = [...IMAGE_MODELS, ...VIDEO_MODELS]

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

export const DEFAULT_MODELS: Record<ModelCapability, string> = {
  'text-to-image': 'google/imagen-4.0-fast',
  'image-to-image': 'black-forest-labs/FLUX.1-kontext-pro',
  'text-to-video': 'google/veo-3.0-fast',
  'image-to-video': 'google/veo-3.0-fast',
}

export function getDefaultModel(capability: ModelCapability): string {
  return DEFAULT_MODELS[capability]
}

export function getModelsForCapability(cap: ModelCapability): AIModel[] {
  return ALL_MODELS.filter(m => m.enabled && m.capabilities.includes(cap))
}

export function getModelById(id: string): AIModel | undefined {
  return ALL_MODELS.find(m => m.id === id)
}

export function getModelCredits(id: string): number {
  const model = getModelById(id)
  return model?.credits ?? 0
}

export function getEnabledModels(type: 'image' | 'video'): AIModel[] {
  return ALL_MODELS.filter(m => m.enabled && m.type === type)
}

export function getModelsByCategory(category: ModelCategory): AIModel[] {
  return ALL_MODELS.filter(m => m.category === category)
}
